### ISSUE TITLE
[Bug]: Combobox not updating state

### ISSUE THREAD

**Issue by lyqht** [radix-vue/shadcn-vue#323] opened 2024-02-05 07:18 UTC
### Reproduction

https://stackblitz.com/~/github.com/lyqht/shacdn-vue-demo

### Describe the bug

All the default behaviors of Combobox component don't work as intended based on [the example given in the documentation](https://www.shadcn-vue.com/docs/components/combobox.html).
- Search doesn't filter
- Selecting command items do not update its internal state
- A default item is not displayed before clicking the combobox

NOTE: Also, there isn't a npx command available for adding this component yet.

### System Info

```bash
System:
    OS: macOS 14.2.1
    CPU: (8) arm64 Apple M2
    Memory: 127.91 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.17.1 - ~/.nvm/versions/node/v16.17.1/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.1.1 - ~/.nvm/versions/node/v16.17.1/bin/npm
    pnpm: 8.14.1 - ~/Library/pnpm/pnpm
    Watchman: 2024.01.15.00 - /opt/homebrew/bin/watchman
  Browsers:
    Brave Browser: 120.1.61.104
    Chrome: 121.0.6167.139
    Safari: 17.2.1
  npmPackages:
    radix-vue: ^1.4.1 => 1.4.1
    vue: ^3.3.11 => 3.4.15
```

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by sadeghbarati** [comment] 2024-02-05 07:30
Your Combobox content is not the same code as documentation code

Check this Stackblitz
https://stackblitz.com/edit/x5v8a8?file=src%2FApp.vue

---

> NOTE: Also, there isn't a npx command available for adding this component yet.

Yes same as other `shadcn` CLIs
The `Combobox` section is more like a demo or documentation around `Command` and `Popover` components

**Comment by sadeghbarati** [comment] 2024-02-05 07:34
https://github.com/radix-vue/shadcn-vue/pull/322

Check this PR too it should fix `hover` and `select` backgrounds

**Comment by lyqht** [comment] 2024-02-05 10:52
> Your Combobox content is not the same code as documentation code
> 
> Check this Stackblitz [stackblitz.com/edit/x5v8a8?file=src%2FApp.vue](https://stackblitz.com/edit/x5v8a8?file=src%2FApp.vue)
> 
> > NOTE: Also, there isn't a npx command available for adding this component yet.
> 
> Yes same as other `shadcn` CLIs The `Combobox` section is more like a demo or documentation around `Command` and `Popover` components

Hello @sadeghbarati, thank you for making a stackblitz demo! It works well there 😊

However, if you refer to the documentation that i linked, my minimal reproducible demo is actually identical to that. Here's an example of the diffs in your demo compared to the documentation. Maybe we should update the docs instead?

![CleanShot 2024-02-05 at 18 49 53@2x](https://github.com/radix-vue/shadcn-vue/assets/35736525/9df32fb6-ec95-4552-8b9b-e3fa4988bebc)

And thanks for making the PR for fixing the styles! I'll try it out.

**Comment by mcrio** [comment] 2024-02-05 11:07
@lyqht In case of issues also make sure to have `radix-vue` updated to latest.

**Comment by sadeghbarati** [comment] 2024-02-05 17:31
If the issue is resolved feel free to close the issue

**Closed as completed** 2024-02-06 01:49 UTC
