### ISSUE TITLE
[Bug]: new version of calendar does not work w last version of radix

### ISSUE THREAD

**Issue by haqaliz** [radix-vue/shadcn-vue#954] opened 2024-12-09 21:57 UTC
### Reproduction

#

### Describe the bug

apcakge.json dependesicies:

"dependencies": {
    "@emotion/css": "^11.13.5",
    "@internationalized/date": "^3.6.0",
    "@popperjs/core": "^2.11.8",
    "@unovis/ts": "^1.4.5",
    "@unovis/vue": "^1.4.5",
    "@vueuse/core": "^12.0.0",
    "@wdns/vue-code-block": "^2.3.3",
    "class-variance-authority": "^0.7.1",
    "date-fns": "^4.1.0",
    "lodash": "^4.17.21",
    "radix-vue": "^1.9.11",
    "tailwind-merge": "^2.5.5",
    "v-calendar": "^3.1.2",
    "vue": "^3.5.13",
    "vuex": "^4.1.0"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^5.2.1",
    "autoprefixer": "^10.4.20",
    "path": "^0.12.7",
    "postcss": "^8.4.49",
    "tailwindcss": "^3.4.16",
    "typescript": "^5.7.2",
    "vite": "^6.0.3"
  }

![image](https://github.com/user-attachments/assets/17a5ff76-2d0b-4ab3-8783-a6edb9b85620)

### System Info

```bash
radix-vue.js?v=e0fe2f45:4232 Uncaught (in promise) TypeError: t.copy is not a function
    at qt (radix-vue.js?v=e0fe2f45:4232:14)
    at setup (radix-vue.js?v=e0fe2f45:7528:13)
    at callWithErrorHandling (chunk-URTEPAQE.js?v=e0fe2f45:2335:19)
    at setupStatefulComponent (chunk-URTEPAQE.js?v=e0fe2f45:10055:25)
    at setupComponent (chunk-URTEPAQE.js?v=e0fe2f45:10016:36)
    at mountComponent (chunk-URTEPAQE.js?v=e0fe2f45:7372:7)
    at processComponent (chunk-URTEPAQE.js?v=e0fe2f45:7338:9)
    at patch (chunk-URTEPAQE.js?v=e0fe2f45:6854:11)
    at ReactiveEffect.componentUpdateFn [as fn] (chunk-URTEPAQE.js?v=e0fe2f45:7482:11)
    at ReactiveEffect.run (chunk-URTEPAQE.js?v=e0fe2f45:553:19)
```

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by sadeghbarati** [comment] 2024-12-11 08:04
It seems to be working with the latest `radix-vue` version in this Stackblitz playground
https://stackblitz.com/edit/utoqutxn


If you still have errors with the latest radix-vue you can try these steps

- remove **packageManager cache**
- remove **node_module** and **lockfile** and reinstall the modules

Or send a reproduction link Thanks 🙏 
Closing for now will reopen after repro

**Closed as not planned by sadeghbarati** 2024-12-11 08:04 UTC
