### ISSUE TITLE
[Bug]: The Carousel element performance presented on www.shadcn-vue.com is different from the one on ui.shadcn.com

### ISSUE THREAD

**Issue by michaelprys** [radix-vue/shadcn-vue#658] opened 2024-07-16 12:49 UTC
### Reproduction

1) https://www.shadcn-vue.com/docs/components/carousel.html, 2) https://ui.shadcn.com/docs/components/carousel

### Describe the bug

If you go to https://www.shadcn-vue.com/docs/components/carousel.html you'll notice that the carousels are laggy compared to the ones on https://ui.shadcn.com/docs/components/carousel.

### System Info

```bash
No output needed for this issue.
```

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by sadeghbarati** [comment] 2024-07-16 15:39
I don't sense the laggy carousel on my end, maybe it could be resolved after this PR gets released 

https://github.com/davidjerleke/embla-carousel/pull/929

**Comment by davidjerleke** [comment] 2024-07-19 11:00
@michaelprys, @sadeghbarati the jitter was accidentally introduced in `v8.1.6` and has been resolved in [`v8.1.7`](https://github.com/davidjerleke/embla-carousel/releases/tag/v8.1.7). Please bump all Embla versions (including plugins)  [here](https://github.com/radix-vue/shadcn-vue/blob/edad815fd9edb787134eac57f5c25079def0c6f5/apps/www/package.json#L32-L33) in the code to `8.1.7`.

- Issue: https://github.com/davidjerleke/embla-carousel/issues/928
- PR that solves the problem: https://github.com/davidjerleke/embla-carousel/pull/933

Best,
David

**Comment by sadeghbarati** [comment] 2024-07-19 12:47
Thanks, David for explaining in such detail ❤️ 

Yes, the issue is solved in `8.1.7`

**Closed as completed by sadeghbarati** 2024-07-19 12:47 UTC
Labels: bug

**Comment by michaelprys** [comment] 2024-07-19 12:56
@davidjerleke Perfect, thank you for the reply!
