### ISSUE TITLE
Update version of TanStack table library

### ISSUE THREAD

**Issue by R0tmayer** [radix-vue/shadcn-vue#700] opened 2024-08-07 01:51 UTC
Hello everyone! 

I have been spending a lot of time trying to figure out **why the data that I pass as props to the DataTable component is not being reactive?** 

_Using Vue Dev Tools, I deleted data from the store, but the table was not updating or rerendering._ 

The problem is older version of the TanStack table in your components ```shadcn-vue/apps/www/package.json```:

 ``` js
"tanstack-table": "^8.19.3"
```

There are also the same issues: 

- [Reactive props for useVueTable](https://github.com/TanStack/table/discussions/4455)
- [[Vue] Pushing to data ref does not add table row ](https://github.com/TanStack/table/issues/4708)
- [docs: make <DataTable /> reactive](https://github.com/radix-vue/shadcn-vue/pull/229)

Support for reactivity in the Vue adapter was added on August 8, 2024 with the release of version:
```js
"@tanstack/vue-table": "^8.20.0"
```
 _Latest version is **v8.20.2**_

Please, update your library's package file to v8.20.0+

**Comment by Taewenn** [comment] 2024-08-07 10:16
Hello, upgraded to "@tanstack/vue-table": "^8.20.2" on my project but still missing reactivity in the DataTable, any updates on this from your side ?

**Comment by Taewenn** [comment] 2024-08-07 10:51
tanstack/vue-table version : "@tanstack/vue-table": "^8.20.2"
(didn't test with previous version)

Ok, I found a workaround : 

- Just go to the `DataTable.vue`
- Add `const data = computed(() => props.data)` (below `props` for example)
- Replace `get data() { return props.data }` by `data` in `const table = useVueTable(...)`

Full working example : 

```
<script setup lang="ts" generic="TData, TValue">
import type { ColumnDef, ColumnFiltersState, SortingState, VisibilityState } from '@tanstack/vue-table'
import { FlexRender, getCoreRowModel, useVueTable, getPaginationRowModel } from '@tanstack/vue-table'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table'
import { valueUpdater } from '@/lib/utils';
import { computed, ref, watch } from 'vue';

const props = defineProps<{
    columns: ColumnDef<TData, TValue>[]
    data: TData[]
}>()
const emit = defineEmits<{
    (e: 'update:selected', value: {}): void;
}>();

const data = computed(() => props.data);

const sorting = ref<SortingState>([])
const columnFilters = ref<ColumnFiltersState>([])
const columnVisibility = ref<VisibilityState>({})
const rowSelection = ref({})

const table = useVueTable({
    data,
    get columns() { return props.columns },
    getCoreRowModel: getCoreRowModel(),
    getPaginationRowModel: getPaginationRowModel(),
    onRowSelectionChange: updaterOrValue => valueUpdater(updaterOrValue, rowSelection),
    state: {
        get sorting() { return sorting.value },
        get columnFilters() { return columnFilters.value },
        get columnVisibility() { return columnVisibility.value },
        get rowSelection() { return rowSelection.value },
    },
})

watch(rowSelection, (newValue) => {
    console.log(newValue);
    emit('update:selected', newValue);
});
</script>
```
The data should now be reactive again 🎉

Maybe it's a little "crappy" but that's the only way I found until now

**Comment by R0tmayer** [comment] 2024-08-07 23:35
> Hello, upgraded to "@tanstack/vue-table": "^8.20.2" on my project but still missing reactivity in the DataTable, any updates on this from your side ?

Hi mate!

I am a backender and my knowledge in the frontend is weak, so could you tell me how to update the library correctly?

Trying this, not working for me:
```js 
npm update
npm update -g "@tanstack/vue-table"
```
Should the component in shadcn-vue automatically update the using TanStack version?

_Also, for the sake of interest, how did you find this issue - through a Google search?_

You can also see a [new comment](https://github.com/TanStack/table/discussions/4455#discussioncomment-10267903) from contributors about this issue

**Comment by sadeghbarati** [comment] 2024-08-08 17:59
@R0tmayer 

You can use 

```shell
npm add @tanstack/vue-table@latest
```

in your Terminal, in your project directory
Close this issue if you solve the problem

Thanks

**Comment by SherMi321** [comment] 2024-08-09 09:01
I have a similar issue. If I use the examples from Tanstack to render the data using plain table it works fine. but if I use Shadcn table components then the reactivity is lost. I don't see the reason why, any ideas?

reproduced my issue: https://stackblitz.com/edit/github-pkcxux

**Comment by R0tmayer** [comment] 2024-08-21 01:27
> tanstack/vue-table version : "@tanstack/vue-table": "^8.20.2" (didn't test with previous version)
> 
> Ok, I found a workaround :
> 
> * Just go to the `DataTable.vue`
> * Add `const data = computed(() => props.data)` (below `props` for example)
> * Replace `get data() { return props.data }` by `data` in `const table = useVueTable(...)`
> 
> Full working example :
> 
> ```
> <script setup lang="ts" generic="TData, TValue">
> import type { ColumnDef, ColumnFiltersState, SortingState, VisibilityState } from '@tanstack/vue-table'
> import { FlexRender, getCoreRowModel, useVueTable, getPaginationRowModel } from '@tanstack/vue-table'
> import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table'
> import { valueUpdater } from '@/lib/utils';
> import { computed, ref, watch } from 'vue';
> 
> const props = defineProps<{
>     columns: ColumnDef<TData, TValue>[]
>     data: TData[]
> }>()
> const emit = defineEmits<{
>     (e: 'update:selected', value: {}): void;
> }>();
> 
> const data = computed(() => props.data);
> 
> const sorting = ref<SortingState>([])
> const columnFilters = ref<ColumnFiltersState>([])
> const columnVisibility = ref<VisibilityState>({})
> const rowSelection = ref({})
> 
> const table = useVueTable({
>     data,
>     get columns() { return props.columns },
>     getCoreRowModel: getCoreRowModel(),
>     getPaginationRowModel: getPaginationRowModel(),
>     onRowSelectionChange: updaterOrValue => valueUpdater(updaterOrValue, rowSelection),
>     state: {
>         get sorting() { return sorting.value },
>         get columnFilters() { return columnFilters.value },
>         get columnVisibility() { return columnVisibility.value },
>         get rowSelection() { return rowSelection.value },
>     },
> })
> 
> watch(rowSelection, (newValue) => {
>     console.log(newValue);
>     emit('update:selected', newValue);
> });
> </script>
> ```
> 
> The data should now be reactive again 🎉
> 
> Maybe it's a little "crappy" but that's the only way I found until now

Updated to latest version using `npm add @tanstack/vue-table@latest`

```js
	"dependencies": {
		"@tanstack/vue-table": "^8.20.4",
```

Change code and it doesn't work.(delete items from pinia store and table doesn't update).  Don't know how to fix thix

```js
const props = defineProps<{
  columns: ColumnDef<TData, TValue>[]
  data: TData[]
}>()

const data = computed(() => props.data);

const table = useVueTable({
  data, // error here
  get columns() {
    return props.columns
  },
  getCoreRowModel: getCoreRowModel(),
  getPaginationRowModel: getPaginationRowModel(),
})
```

`Vue: Type ComputedRef<TData[]> is missing the following properties from type TData[]: length, pop, push, concat, and 29 more`

[This variant ](https://github.com/TanStack/table/discussions/4455#discussioncomment-10282636) give me the same error:

```js
const props = defineProps<{
  columns: ColumnDef<TData, TValue>[]
  data: TData[]
}>()

const {data} = toRefs(props);

const table = useVueTable({
  data, // error here
  get columns() {
    return props.columns
  },
  getCoreRowModel: getCoreRowModel(),
  getPaginationRowModel: getPaginationRowModel(),
})
```

`Vue: Type Ref<TData[]> is missing the following properties from type TData[]: length, pop, push, concat, and 29 more.`

**Comment by Azurox** [comment] 2024-08-21 21:08
Same problem here, even adding a key on table with a generated hash can't force a re-render of the table :(

**Comment by SherMi321** [comment] 2024-08-22 12:03
I have made it work with the following code:

```js
const props = defineProps<{
  columns: ColumnDef<TData, TValue>[]
  data: TData[]
}>()

const table = useVueTable({
  data: toRef(props,'data'),
  get columns() { return props.columns },
  getCoreRowModel: getCoreRowModel(),
  getFilteredRowModel: getFilteredRowModel(),
})
```

**Comment by hrynevychroman** [comment] 2024-08-30 15:06
To be clear, I don't think this issue is related to the UI library; all needed info is described inside the [official stack/table docs](https://tanstack.com/table/latest/docs/framework/vue/guide/table-state#using-reactive-data), where you can find an example and how to deal with it.

Video example:
https://github.com/user-attachments/assets/02112b99-a41d-4167-954b-10caa675b989

@sadeghbarati I think we could close this issue as it is not related to shadcn-vue at all 😅

**Comment by sadeghbarati** [comment] 2024-08-30 18:56
Make sense, but we need to update doc


- https://tanstack.com/table/latest/docs/framework/vue/guide/table-state#using-reactive-data
- https://github.com/TanStack/table/pull/5687#issuecomment-2281067245

**Closed as completed** 2024-08-31 07:31 UTC
Labels: documentation
